"""Typed structured-output contracts shared by text providers."""

from __future__ import annotations

import json
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, ValidationError

from ai_toolkit._structured import parse_json
from ai_toolkit.types import AIToolkitError, ChatCompletionResult

StructuredOutputStage = Literal["json_decode", "validation"]


class JsonOutputModel(BaseModel):
    """Base class for JSON outputs generated by text models."""

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

    @classmethod
    def prompt_fragment(cls) -> str:
        """Render a compact JSON-shaped instruction for prompt composition."""
        schema = cls.model_json_schema()
        properties = schema.get("properties")
        if not isinstance(properties, dict):
            properties = {}

        example = {
            field_name: _prompt_example_value(field_name, field_schema)
            for field_name, field_schema in properties.items()
            if isinstance(field_schema, dict)
        }
        example_text = json.dumps(example, ensure_ascii=False, indent=2)
        return (
            "只返回以下结构的 JSON 对象，不要输出解释或 Markdown：\n\n"
            f"{example_text}"
        )


class StructuredOutputError(AIToolkitError):
    """Raised when a model response cannot satisfy a JsonOutputModel."""

    def __init__(
        self,
        *,
        output_type: type[JsonOutputModel],
        stage: StructuredOutputStage,
        completion: ChatCompletionResult,
        detail: str,
    ) -> None:
        self.output_type = output_type
        self.stage = stage
        self.completion = completion
        self.detail = detail
        super().__init__(
            f"{output_type.__name__} structured output failed "
            f"during {stage}: {detail}"
        )


def output_schema(
    *,
    schema: dict[str, Any] | None,
    output_type: type[JsonOutputModel] | None,
) -> dict[str, Any] | None:
    """Resolve the provider schema while keeping legacy schema calls intact."""
    if schema is not None and output_type is not None:
        raise ValueError("schema and output_type cannot be used together")
    if output_type is None:
        return schema
    if not isinstance(output_type, type) or not issubclass(
        output_type,
        JsonOutputModel,
    ):
        raise TypeError("output_type must inherit from JsonOutputModel")
    return output_type.model_json_schema()


def validate_output_model(
    completion: ChatCompletionResult,
    output_type: type[JsonOutputModel],
) -> ChatCompletionResult:
    """Parse and validate a completion, raising on structured-output errors."""
    parsed = parse_json(completion.text)
    if parsed is None:
        detail = "model did not return valid JSON"
        completion.schema_error = detail
        raise StructuredOutputError(
            output_type=output_type,
            stage="json_decode",
            completion=completion,
            detail=detail,
        )

    completion.parsed_json = parsed
    try:
        completion.output = output_type.model_validate(parsed)
    except ValidationError as error:
        detail = _validation_error_detail(error)
        completion.schema_error = detail
        raise StructuredOutputError(
            output_type=output_type,
            stage="validation",
            completion=completion,
            detail=detail,
        ) from error

    return completion


def _prompt_example_value(
    field_name: str,
    field_schema: dict[str, Any],
) -> Any:
    description = field_schema.get("description")
    label = (
        description.strip()
        if isinstance(description, str) and description.strip()
        else field_name
    )

    examples = field_schema.get("examples")
    if isinstance(examples, list) and examples:
        return examples[0]
    if "example" in field_schema:
        return field_schema["example"]
    if "const" in field_schema:
        return field_schema["const"]

    enum_values = field_schema.get("enum")
    if isinstance(enum_values, list) and enum_values:
        return enum_values[0]

    value_type = field_schema.get("type")
    if not isinstance(value_type, str):
        value_type = _first_non_null_type(field_schema)

    if value_type == "string":
        return f"<{label}>"
    if value_type == "integer":
        return 0
    if value_type == "number":
        return 0.0
    if value_type == "boolean":
        return False
    if value_type == "array":
        return []
    if value_type == "object":
        return {}
    return None


def _first_non_null_type(field_schema: dict[str, Any]) -> str | None:
    variants = field_schema.get("anyOf")
    if not isinstance(variants, list):
        return None

    for variant in variants:
        if not isinstance(variant, dict):
            continue
        value_type = variant.get("type")
        if isinstance(value_type, str) and value_type != "null":
            return value_type
    return None


def _validation_error_detail(error: ValidationError) -> str:
    messages: list[str] = []
    for item in error.errors(
        include_url=False,
        include_context=False,
        include_input=False,
    ):
        location = ".".join(str(part) for part in item.get("loc", ()))
        message = str(item.get("msg", "invalid value"))
        messages.append(f"{location or '<root>'}: {message}")
    return "; ".join(messages) or "output validation failed"
